// Include a Table of Contents on the left hand side.
:toc: left
// ":icons: font" is needed for admonition and callout icons.
:icons: font

= Exploration of CockroachDB for the control plane database

See https://53.rfd.oxide.computer/[RFD 53 ("Control plane data storage requirements")] for background.

See https://110.rfd.oxide.computer/[RFD 110 ("CockroachDB for the control plane database")] for the results of this testing.

== This repo

The code in this repo uses Terraform to provision a multi-node CockroachDB cluster on AWS, using OmniOS and https://sysmgr.org/~jclulow/tmp/cockroach.tar.gz[Joshua's CRDB binaries].  This covers:

* terraform configuration to deploy the whole thing
* working illumos builds (and configuration and SMF manifests) for:
** cockroachdb
** Prometheus
** Grafana
** sysbench
** chrony
** Prometheus's node_exporter
* monitoring:
** generic VM metrics: boot time, CPU utilization, etc.
** illumos-specific metrics: I/O latency and utilization, network throughput
** CockroachDB metrics
** Grafana and Prometheus metrics
** many of these use AWS-based service discovery

== Using this repo

To deploy a cluster, you need to have:

- terraform configured using your AWS account
- an ssh key configured in AWS called "dap-terraform" OR change locals.ssh_key_name in terraform/nodes.tf to refer to your key's name
- a bunch of binaries downloaded by hand into this repo.  There's not a great way to assemble this yet, but .gitignore can tell you what they are and where they go.

**With those prerequisites in place**, you can construct the tarball to be used on each host:

[source,text]
----
$ cd vminit
$ make
----

Then upload these to the S3 bucket:

[source,text]
----
$ aws s3 cp vminit-common.tgz s3://oxide-cockroachdb-exploration/vminit-common.tgz
$ aws s3 cp vminit-cockroachdb.tgz s3://oxide-cockroachdb-exploration/vminit-cockroachdb.tgz
$ aws s3 cp vminit-mon.tgz s3://oxide-cockroachdb-exploration/vminit-mon.tgz
----

Then use terraform to deploy the cluster:

[source,text]
----
$ cd terraform
$ terraform apply
----

This will emit the public and private IPs of all the nodes in the cluster.  Note the private IP address of any of the database nodes, then log into the load generator and run:

[source,text]
----
$ ssh root@$LOADGEN_PUBLIC_IP
$ configure_cluster --host DB_PRIVATE_IP
----


== Known issues

* cockroachdb: We're currently working on a build from master from the summer.  We should switch to a release build and make sure we're exercising Pebble.  (We are exercising Pebble now, but if we switch to the latest release as of this writing, we will be back on RocksDB.)
* cockroachdb: Readline functionality (e.g., up arrow to see previous command) doesn't work in `cockroach sql` shell
* this repo: None of this is currently easily reproducible from scratch because setting up the VMs relies on several tarballs built from this repo, but the contents of them don't exist in this repo (because it would involve checking in a bunch of large binaries that we don't want to carry on forever).  The best solution I've come up with for this is to put these binaries into a submodule that's incorporated here.  That way, people casually working on the repo don't need to download these binaries (and we don't necessarily need to download them forever when we clone, even if we change the way all this works), but it'll still all be present.
* chrony setup: Sometimes a cold start of the VMs leaves CockroachDB in maintenance, having crashed because its clock was too far out of sync.  This should not be possible because we're starting chrony and configuring it to wait until it has successfully sync'd the clock (with step, not slew) _before_ starting CockroachDB on all nodes.  Still, it happens sometimes.
* cockroachdb: Before you've initialized the CRDB cluster, if you go to the adminui, you get a very blank 404 page
* terraform: we sometimes hit: https://github.com/terraform-providers/terraform-provider-aws/issues/12533. Retrying `terraform apply` has worked around the issue.
* cockroachdb: I tried activating statement diagnostics for an UPSERT that one of the workloads runs to see what that does.  This produced a bundle that was 23 bytes (0 bytes downloaded, for some reason).  This may have been a known bug (see raw notes file) but I'm not sure.  https://www.youtube.com/watch?v=xUw8dN-yJU4&feature=emb_logo[There's a good, short video showing the data in these bundles.]
* cockroachdb: flags for the `cockroach workload` command do not match the online docs

CockroachDB recently changed the default from RocksDB to PebbleDB, despite the documentation (even for the build that I'm using) not having been updated to reflect that.

== For further digging

* https://www.cockroachlabs.com/docs/v20.1/cluster-setup-troubleshooting#capacity-planning-issues[Capacity planning issues]
* https://www.cockroachlabs.com/docs/v20.1/cluster-setup-troubleshooting#memory-issues[Memory issues].

See also the open questions in the report.

Is it worth trying to see what happens when it runs out of disk space by putting its text log and data on separate filesystems and seeing what it logs?  See 9/30 for description of apparent corruption when this happens, including data lost _after_ the corruption was supposedly repaired.

== CockroachDB Caveats

* Currently https://www.cockroachlabs.com/docs/v20.1/recommended-production-settings#storage[limited to 4 TiB of storage per node].
* https://www.cockroachlabs.com/docs/v20.1/known-limitations.html#cold-starts-of-large-clusters-may-require-manual-intervention[Ugly looking bug around cluster startup]
* https://www.cockroachlabs.com/docs/v20.1/rename-table#table-renaming-considerations[Table renaming is not transactional]


== References

* https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-aws.html[CockroachDB on AWS]
* https://kbild.ch/blog/2019-02-18-awsprometheus/[Prometheus on AWS].
* https://www.slideshare.net/mitsuhirotanda/prometheus-on-aws-63736540[Prometheus on AWS] (slide deck)
* https://github.com/oxidecomputer/storage-exploration[Adam's Terraform config for storage exploration]
* https://aws.amazon.com/ec2/instance-types/[AWS Instance Types]
* https://github.com/oxidecomputer/confomat-oxide[Josh's confomat stuff]
* http://wiki.omniosce.org/GeneralAdministration[OmniOS administration]
* https://console.aws.amazon.com/ec2/v2/home?region=us-west-2#Instances:sort=instanceId[AWS EC2 console (us-west-2)]
* https://www.terraform.io/docs/cli-index.html[Terraform CLI docs]
* https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html[AWS describe-instances CLI]
* https://github.com/prometheus/haproxy_exporter#official-prometheus-exporter[haproxy Prometheus support]
